# Generated by Django 3.0.3 on 2020-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_magazine_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='image',
            new_name='magazine_image',
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
