# Generated by Django 3.0.3 on 2020-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_auto_20200330_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
    ]
