# Generated by Django 3.0.3 on 2020-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_book_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
