# Generated by Django 3.0.3 on 2020-04-03 21:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0009_auto_20200403_2144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookTracker',
            new_name='Book_Tracker',
        ),
    ]
