# Generated by Django 3.0.3 on 2020-04-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0014_auto_20200404_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInstance',
        ),
    ]
