# Generated by Django 3.0.3 on 2020-04-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0015_delete_bookinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
