# Generated by Django 3.0.3 on 2020-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0016_auto_20200404_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
