# Generated by Django 3.0.3 on 2020-04-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0017_book_borrowed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_date',
        ),
    ]
