# Generated by Django 3.0.3 on 2020-04-04 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0018_remove_book_borrowed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='name',
        ),
        migrations.AddField(
            model_name='magazine',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazine',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='magazine',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
