# Generated by Django 3.0.3 on 2020-04-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
